### ISSUE TITLE
Data for the pouring task

### ISSUE THREAD

**Issue by lzylucy** [JunzheJosephZhu/see_hear_touch#3]
Hello!

I'm wondering where to find data for the pouring task described in the paper. The example dataset seems to be all for a peg insertion task. Thank you!

**Comment by JunzheJosephZhu** [comment]
https://drive.google.com/drive/folders/1_zMdgKx2eKCaDbicKwWuaWcC7MFVka9W?usp=sharing

**Comment by JunzheJosephZhu** [comment]
@HaoLiRobo Could you check if this link contains the correct data? Thanks!

**Comment by hao-l1** [comment]
Hi, Thanks for the questions!

Here is an example data for the pouring task. You might need to collect your own data since the setting might be different in your lab.
https://drive.google.com/drive/folders/1VaEavQlgeVFaVrEsZ649nmofzGJuOAHP?usp=sharing

**Comment by lzylucy** [comment]
Hi @JunzheJosephZhu and @HaoLiRobo, thanks for the reply and sharing the data!
